### ISSUE TITLE
MKR1000 works with 1.1.6, but not with 1.1.7

### ISSUE THREAD

**Issue by AugustoEst** [arduino-libraries/Temboo#8]
My Temboo code was working fine with the **1.1.6** version of the library. I was using the MKR1000 and the Windows IDE (1.6.11).

I am now using **Arduino Create**, which uses the latest Temboo library (**1.1.7**). This causes the following error: 

```
/home/admin/builder/arduino-builder/latest/Temboo-1.1.7/src/TembooMonitoring.cpp:320:32: error: 'dtostrf' was not declared in this scope

dtostrf(pinVal, 4, 2, floatStr); 
```

**Comment by AugustoEst** [comment]
I've fixed this issue in https://github.com/AugustoEst/Temboo 

The problem is that it forces people to upload this version of the library to Arduino Create, instead of using the core library.

**Comment by cormacdriver-temboo** [comment]
Thanks for this. I'll duplicate the issue in our internal dev repo and close this issue out. We'll address it in our next library release.
